### PR TITLE
Expired timers are no longer returned by the API

### LINKED ISSUE #108: timer switch entity not working with 2.0.0-beta1
Hello,

I haven't had a chance to look into this yet but it seems that the 2.0.0 beta breaks the timer switch (it's just always off) everything else appears to work fine, and there's no errors in the logs.

### PR DESCRIPTION
**Pull request by Cadair**
This seems to fix #108 for me

The related change in babybuddy is: https://github.com/babybuddy/babybuddy/commit/7b7f17fde6cc6c45a36752cbf1b2752fe396476d

What's the best way to handle supporting both <2 and 2 at the same time?

### CODE REVIEW

**Comment by Cadair** [comment]
@jcgoette Looks like the final release of 2.0 isn't that far away, have you had a chance to look at this?

The only thing I haven't done with it is tested it against a 1.x release.

**Comment by jcgoette** [comment]
Yes, this looks good to me. If you can test against v1.x.x, should be good to go.

**Comment by Cadair** [comment]
Not sure when i will get around to spinning up a test instance. If anyone has one they could test against that would be super useful.

**Comment by jcgoette** [comment]
Did some prelim testing on pre- and post- v2.0 and looks good to me. My only thought is should we remove the Timers sensor now, since completed sensors are now deleted?

**Comment by Cadair** [comment]
I think the `_last_timer` sensor is now pretty much a duplication of the attributes of the switch?

**Pull request merged**
