### PR TITLE
Generate sensors for BabyBuddy timers

### PR DESCRIPTION
**Pull request by torrancew**
This PR would address #37. I've tested the change out in a local HA container and verified that it seems to do what I intended. Let me know if there is further validation you'd like to see, or if there was a concrete reason to not expose the last timer as a sensor, as is done with feedings, changes & tummy time.

### CODE REVIEW

**Comment by jcgoette** [comment]
I'm okay with this, but what should the state of the sensor be? I don't like `True`/`False`.

**Comment by torrancew** [comment]
After playing around with the resulting entities, I agree with you. `true`/`false` is also at odds with the `timestamp` device_class. I do think it's worth surfacing `active` as an attribute.

I'd propose either:
* `duration`
* `start`

Most likely, I'll use `start` for my UIs so that duration can be computed client-side and appear more real-time. What do you think?

**Comment by engrbm87** [comment]
The switch entity includes all the attributes that the user needs. Creating a sensor with state (active/not active) would not provide anything new as the switch state already provides this. I suggest simply using the [attribute](https://www.home-assistant.io/lovelace/entities/#attribute) option in the entities card in lovelace.

**Comment by jcgoette** [comment]
You're correct @engrbm87, but that only works while the switch entity is `on` (unless there is something basic I'm missing).

**Comment by engrbm87** [comment]
Hello @jcgoette , @torrancew wanted to get the duration of a running timer. It is intentional to only display the attributes when we have an active/running timer. Stopped timers should not be used to add a new entry (like sleep or feeding).
I hope this clarifies this point.

**Comment by torrancew** [comment]
I did not realize that the switch carried additional attributes when it was `on` -- however, I intend to integrate this specific feature with the "Time Elapsed" custom Lovelace card in HACS, and the limitations of that card require a sensor of device class `timestamp`, or an `input_datetime`. Surfacing sensors of this nature would keep me from shimming in awkward template sensors that use some sort of sentinel value when the switch is off & the true attributes unavailable.

**Comment by jcgoette** [comment]
I tend to agree with bringing back sensor._last_timer that [existed back in v1.4.0 and prior](https://github.com/jcgoette/baby_buddy_homeassistant/blob/54acdc444dbaeff2eecb4d2d7ee25ed239e57d9c/custom_components/babybuddy/const.py#L11).

@torrancew, please update code to use `start`, as that was what was used in v1.4.0 and prior. Also, test with using timer service to pass data back, both with timer on and off. I think we'll be fine if we don't modify this portion:

https://github.com/jcgoette/baby_buddy_homeassistant/blob/1b349f01aad7579080794a84b979a6362db73ea7/custom_components/babybuddy/switch.py#L278-L281

**Comment by engrbm87** [comment]
This would break the switch state. You need to create a separate entity description for the timer sensor.

**Comment by torrancew** [comment]
@engrbm87 Could you clarify which change you're concerned with here? The one I've committed, or the paste @jcgoette provided earlier?

Some cursory testing shows that the branch in its current state does not appear to have any negative effect on the switch state. I will test interactions with the other services this evening.

**Comment by engrbm87** [comment]
Checking the code again it seems the switch entity is not using the entity_description. I think you are safe to proceed with these changes.

**Comment by torrancew** [comment]
Verified the following over lunch:
* Adding an activity that uses an active timer works as expected (activity is added, timing info appears accurate)
* Adding an activity that ignores an active timer works as expected (activity is added, timing info is not related to the timer)
* Adding an activity that does not use a timer when there is no timer works as expected (activity added, timing info is appropriate)
* Adding an activity that uses a timer when there is no timer works as expected (no activity is created)

Along the way, I noticed the descriptions are a bit off for the service inputs for `service.baby_buddy_add_tummy_time`. Will send a separate PR to clean those up.

**Comment by jcgoette** [comment]
This looks good to me; thanks @torrancew!

**Pull request merged**
