### PR TITLE
add support for babybuddy sub directory url

### PR DESCRIPTION
**Pull request by paradox00**
Signed-off-by: Aviv BD <bd.aviv@gmail.com>

### CODE REVIEW

**Comment by paradox00** [comment]
@jcgoette  - I'm hoping you would accept this PR. My babybuddy is installed with subdirectory, this change is live on my setup for 2 weeks now.

If you have any suggestion or comments I'll be happy to listen.

**Comment by jcgoette** [comment]
Please review the failed CI checks.

**Comment by paradox00** [comment]
Since i rebased this pr the previous CI checks failures disappeared... Can you allow them to run again?

**Comment by jcgoette** [comment]
Thanks for your contribution!

**Pull request merged**
